a = int(input("число 1: "))
b = int(input("число 2: "))
print(a + b)
print(a - b)
print("a == b", a == b)
print("a != b", a != b)
print("a <= b", a <= b)
print("a => b", a >= b)
print("a < b", a < b)
print("a > b", a > b)